#!/bin/bash
set -e

TestAndCreateDir() {
    if [ ! -d $1 ]; then
        #echo "Directory $1 does not exist. Creating it.";
        mkdir -p $1;
    fi
}


if test $# -ne 1
then
  echo "Usage: install-civs <settings-file>";
  exit 1;
fi

echo "Read settings file."
. $1 || exit 1

if test -z "$ADMIN_KEY"
then
    echo 'ERROR: Must define $ADMIN_KEY in' $1 'to be something secret.'
    exit 1
fi

make -s gettimeofday timeout lockserv

TestAndCreateDir $HTMLDIR;
TestAndCreateDir $CGIBINDIR;
TestAndCreateDir $CIVSDATADIR;
TestAndCreateDir $CIVSDATADIR/elections;
TestAndCreateDir $CIVSDATADIR/invites;

for f in elections/admission_control lockserv
do
    if [ -e $CIVSDATADIR/$f ]; then
        rm $CIVSDATADIR/$f
    fi
done

    for f in civs_create.html* index.html* public_elections.html*	      \
        proportional.html* sec_priv.html* acks.html changelog.html*	      \
        news.html* *.var rp.html* publicized_polls.html* faq.html*	      \
        style.css results.js vote.js ajax.js ezdom.js civs_hdr.js	      \
        mail_mgmt.js opt_in.js add_voters.js hebrew.css
    do
	case "$f" in
	  *.var)    dest="${HTMLDIR}/${f}";;
	  *.html.*) dest="${HTMLDIR}/${f}${UTF8_SUFFIX}";;
	  *.html)   dest="${HTMLDIR}/${f}${EN_SUFFIX}";;
	  *)        dest="${HTMLDIR}/${f}";;
	esac
	echo "copying $f to $dest"
	sed  -e 's|@PERL@|'$PERL'|' \
	     -e 's|@CGIBINDIR@|'$CGIBINDIR'|'\
	     -e 's|@PROTO@|'$PROTO'|' \
	     -e 's|@THISHOST@|'$THISHOST'|' \
	     -e 's|@CIVSDATADIR@|'$CIVSDATADIR'|' \
	     -e 's|@CIVSBINURL@|'$CIVSBINURL'|' \
	     -e 's|@CIVSURL@|'$CIVSURL'|' \
	     -e 's|@CIVSHOME@|'$CIVSHOME'|' \
	     -e 's|@SUPERVISOR@|'$SUPERVISOR'|' \
	     -e 's|@AUTH_SENDER@|'$AUTH_SENDER'|' \
	     -e 's|@ADMIN_KEY@|'$ADMIN_KEY'|' \
	     -e 's|@SMTP_HOST@|'$SMTP_HOST'|' \
	     -e 's|@SMTP_PORT@|'$SMTP_PORT'|' \
	     -e 's|@SMTP_USE_SSL@|'$SMTP_USE_SSL'|' \
	     -e 's|@SMTP_AUTH_USER@|'$SMTP_AUTH_USER'|' \
	     -e 's|@SMTP_AUTH_PASSWD@|'$SMTP_AUTH_PASSWD'|' \
	     -e 's|@LOCALDEBUG@|'$LOCALDEBUG'|' \
	     -e 's|@ADDTOPATH@|'$ADDTOPATH'|' \
	     -e 's|@PERLEXT@|'$PERLEXT'|' \
	     -e 's|@USING_ISA@|'$USING_ISA'|' \
	     -e 's|@FILTER_TAGS@|'$FILTER_TAGS'|' \
	     -e 's|@MAX_VOTER_ADD@|'$MAX_VOTER_ADD'|' \
	     -e 's|@MAX_EMAIL_LOAD@|'$MAX_EMAIL_LOAD'|' \
	     -e 's|@MAX_IMAGE_SIZE@|'$MAX_IMAGE_SIZE'|' \
	     -e 's|@LOG_HOME_VISITS@|'$LOG_HOME_VISITS'|' \
	     -e 's|@SUGGESTION_BOX@|'$SUGGESTION_BOX'|' \
	     -e 's|@DONATE_URL@|'$DONATE_URL'|' \
	     -e 's|@UTF8_SUFFIX@|'$UTF8_SUFFIX'|' \
	< "$f" > "$dest"
    done

    echo "copying:"
    for f in add_voters beatpath.pm beatpath2.pm civs_common.pm		      \
        voting.pm close control create_election download_ballots	      \
        remove_writein upload_ballots results top_polls.pm		      \
        get_top_polls languages.pm election.pm mail.pm start_election	      \
        vote refresh_top_polls mail_mgmt opt_in publicize_election	      \
        status clear_caches delete_election.pl edit_poll		      \
        remove_defunct_elections request_deactivation request_activation      \
        resend_link send_result_key.pm rp.pm runoff.pm minimax.pm	      \
        admctrl.pm base_language.pm english.pm hungarian.pm italian.pm	      \
        french.pm german.pm hebrew.pm portuguese.pm chinese.pm		      \
        spanish.pm thai.pm russian.pm
    do
	target="${CGIBINDIR}/${f}"
	if test -n "$PERLEXT"
	then
	    case $target in
	      *.pm) ;;
	      *.pl) ;;
	      *) target="${target}${PERLEXT}";;
	    esac
	fi
	echo " ->$target"
	sed  -e 's|@PERL@|'$PERL'|' \
	     -e 's|@CGIBINDIR@|'$CGIBINDIR'|'\
	     -e 's|@PROTO@|'$PROTO'|' \
	     -e 's|@THISHOST@|'$THISHOST'|' \
	     -e 's|@CIVSDATADIR@|'$CIVSDATADIR'|' \
	     -e 's|@CIVSBINURL@|'$CIVSBINURL'|' \
	     -e 's|@CIVSURL@|'$CIVSURL'|' \
	     -e 's|@CIVSHOME@|'$CIVSHOME'|' \
	     -e 's|@SUPERVISOR@|'$SUPERVISOR'|' \
	     -e 's|@ADMIN_KEY@|'$ADMIN_KEY'|' \
	     -e 's|@SMTP_HOST@|'$SMTP_HOST'|' \
	     -e 's|@SMTP_PORT@|'$SMTP_PORT'|' \
	     -e 's|@SMTP_USE_SSL@|'$SMTP_USE_SSL'|' \
	     -e 's|@SMTP_STARTTLS@|'$SMTP_STARTTLS'|' \
	     -e 's|@SMTP_AUTH_USER@|'$SMTP_AUTH_USER'|' \
	     -e 's|@SMTP_AUTH_PASSWD@|'$SMTP_AUTH_PASSWD'|' \
	     -e 's|@AUTH_SENDER@|'$AUTH_SENDER'|' \
	     -e 's|@LOCALDEBUG@|'$LOCALDEBUG'|' \
	     -e 's|@ADDTOPATH@|'$ADDTOPATH'|' \
	     -e 's|@PERLEXT@|'$PERLEXT'|' \
	     -e 's|@USING_ISA@|'$USING_ISA'|' \
	     -e 's|@FILTER_TAGS@|'$FILTER_TAGS'|' \
	     -e 's|@MAX_VOTER_ADD@|'$MAX_VOTER_ADD'|' \
	     -e 's|@MAX_EMAIL_LOAD@|'$MAX_EMAIL_LOAD'|' \
	     -e 's|@MAX_IMAGE_SIZE@|'$MAX_IMAGE_SIZE'|' \
	     -e 's|@LOG_HOME_VISITS@|'$LOG_HOME_VISITS'|' \
	     -e 's|@SUGGESTION_BOX@|'$SUGGESTION_BOX'|' \
	     -e 's|@DONATE_URL@|'$DONATE_URL'|' \
	 	 < "cgi-bin/$f" > "$target"
	chmod a+x "$target"
	installed="$installed $target"
    done
    mkdir -p "${HTMLDIR}/images"
    for f in images/{check123b,sample-ballot,vertstrip,check-civs}.png;
    do
	dest="${HTMLDIR}/${f}"
        cp "$f" "$dest"
    done
    echo

    if [ ! -s $CIVSDATADIR/private_host_id ]; then
	echo "*********************************************";
	echo "                 WARNING                     ";
	echo "*********************************************";
	echo "";
	echo "No private key exists for the server!";
	echo "";
	echo "Creating a private key using the openssl pseudo-random number";
	echo "generator.  If you want more randomness than this, you will";
	echo "need to create your own key.  See the INSTALL file for more";
	echo "information."
	echo "";
	openssl rand -base64 -out $CIVSDATADIR/private_host_id 32;
	echo "*********************************************";
    fi

	if [ ! -s $CIVSDATADIR/nonce_seed ]; then
		echo "Seeding the CIVS nonce generator.";
		openssl rand -hex -out $CIVSDATADIR/nonce_seed 32;
	fi

    touch $CIVSDATADIR/nonce_seed $CIVSDATADIR/log $CIVSDATADIR/cgi-log $CIVSDATADIR/global_lock
    chmod ugo+w $CIVSDATADIR/nonce_seed $CIVSDATADIR/log $CIVSDATADIR/cgi-log $CIVSDATADIR/global_lock

    for f in gettimeofday timeout lockserv
    do
        if [ -e "$f".exe ]; then
            cp "$f".exe $CIVSDATADIR/
        else
            cp "$f" $CIVSDATADIR/
        fi
    done

    # Test resulting installed scripts, after everything has been
    # installed.
    log="$CIVSDATADIR/cgi-log"
    cp "$log" "$log".test
    syntax=
    for f in $installed
    do
        # Catch and report redirected errors (either redirected
        # directly or via BEGIN).
        rm "$log"
        touch "$log"
        fail=
        if ! perl -I "${CGIBINDIR}" -c "$f" >/dev/null 2>>"$log"; then
            fail=1
        fi
        cat "$log"
        unexpected_lines=$(grep -v "syntax OK" -- "$log" | wc -l)
        if [ "$unexpected_lines" -gt 0 ]; then
            fail=1
        fi
        if [ -n "$fail" ]; then
            syntax="$syntax $f"
        fi
    done
    mv "$log".test "$log"
    if [ -n "$syntax" ]; then
        echo "Syntax checking failures: $syntax"
        exit 1
    fi
    echo

echo "Install completed.  Check for any errors reported above.";
